image: golang:buster

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/tceu-chriswest/sops

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  # move the vault tests out of the way to spare our blushes with d-in-d
  # shenanigans
  - mv hcvault/keysource_test.go /tmp

after_script:
  - mv /tmp/keysource_test.go hcvault/

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - sops
